baseURL = "https://example.com"
languageCode = "en-us"
title = "Showcase Theme"
Paginate = 1000
googleAnalytics = ""
theme = "showcase-hugo-theme"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "showcase"
  description = "Minimal, one page, theme for showcasing your work"
  message = ""
  hideAutoMenu = false

[[menu.main]]
  name = "External"
  url = "https://example.com"

[social]
  facebook = "https://facebook.com/imt.innovlab"
  twitter = "https://twitter.com/imt_innovlab"
  instagram = "https://instagram.com/imt_innovlab"
  linkedin = "https://linkedin.com"
